### ISSUE TITLE
Up to v0.10 only?

### ISSUE THREAD

**Issue by Trott** [AlexeyKupershtokh/node-candle#2]
This module works fine for me in Node v0.10 but not in Node v0.12 or later. Is that correct or might I be Doing Something Wrong?

Here's my sample code that works fine on v0.10 but not on v0.12:

````
var Candle = require('candle');

var c = new Candle;
var id = c.add(function() {
  console.log('foo');
});
c.setTimeout(id, 1);
````

Run with Node v0.10, this code logs `foo` as expected. 

Run with Node v0.12, I get:

    Assertion failed: (cb_v->IsFunction()), function MakeCallback, file ../src/async-wrap-inl.h, line 108.
    Abort trap: 6

Run with Node 4.1.1, I get:

    Assertion failed: (cb_v->IsFunction()), function MakeCallback, file ../src/async-wrap-inl.h, line 76.
    Abort trap: 6

**Comment by AlexeyKupershtokh** [comment]
Could you try to change the `timers` module inclusion to the original one: https://github.com/AlexeyKupershtokh/node-candle/blob/master/candle.js#L3 and try again?

**Comment by AlexeyKupershtokh** [comment]
Yeah, that was the problem. I've fixed it in the v0.4.0 version.
PS: I haven't touched this project for 3 years since node.js 0.9 times.

**Comment by Trott** [comment]
Cool, that works. So with that change, the `timers.js` file in the source code is no longer needed, right?

**Comment by AlexeyKupershtokh** [comment]
Exactly. I'll cleanup it later. Maybe.
